---
title: "Getting data in and out of Shiny"
author: "Megsie Siple"
date: "February 17, 2019"
output: 
  ioslides_presentation:
    widescreen: true
---

## Bringing data into Shiny
If you want to design your app so that people can bring in their own data:

Add a file upload input in the UI using the function `fileInput()`, e.g. `fileInput('mydata')`. In the server function, access the uploaded files via `input$mydata`:
```
ui <- fluidPage(

  # App title ----
  titlePanel("Uploading Files"),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      # Input: Select a file ----
      fileInput("file1", "Choose CSV File",
                multiple = FALSE,
                accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv")),
```

## Getting data out of Shiny


## Example for getting data out


##My :roll_eyes: can be your :heavy_check_mark:
 - if you have a total crash when publishing, check your parentheses! )} then check your commas. 
 - 
 - other helpful pointers...?

## Other useful tips and tricks
 - `print()` to the RStudio console to confirm that objects are what you think they are
 - if you want to save data or outputs and use in several server operations, use `reactive` 
 - use `kableExtra` to make nice tables
 - use `ggplotly` to make interactive plots (e.g., click to see data)
 
## Overall Shiny: helpful resources
 - Dean Attali's [Shiny tutorial](https://deanattali.com/blog/building-shiny-apps-tutorial/) and general Shiny advice 
 - DataCamp has a couple of free online [Shiny courses](https://www.datacamp.com/search?q=shiny), including a lesson on building dashboards 
 - For `leaflet` in Shiny, the [Rstudio leaflet intro](https://rstudio.github.io/leaflet/shiny.html)